### ISSUE TITLE
stops working after 1000 plays

### ISSUE THREAD

**Issue by timoteo1994** [darkxex/mediafireStream#3]
because it stops working after having 1000 reproductions, looking at the file in mediafire it has more than 1000 downloads and it no longer plays

**Comment by darkxex** [comment]
porque al ser una página web, las 1000 reproducciones vienen de la misma ip, por lo que mediafire lo bloquea, si quieres saltarte eso, lo mejor sería reescribir el código para que se ejecute como un javascript, de ese modo cada acceso tendría una ip diferente. saludos.

**Comment by timoteo1994** [comment]
como podria reescribirlo?? hasta ahortia la solucion que he estado realizando es copiar el video en otra carpeta de la misma cuenta como me una un id diferente si funciona

**Comment by timoteo1994** [comment]
entonces deberia usar codigos javaescrbir y hacer el mismo procreso y ai ya mediafire ya no me bloqueria??

**Comment by darkxex** [comment]
en teoría sí, lo que pasa es que el código actual es php, y el php se ejecuta en el servidor, o sea tu página web, esa página siempre tendrá la misma ip. por ende mediafire la detecta y la bloquea, en cambio javascript se ejecuta en el navegador del que accede a la página web, por ende cada persona que entra a tu página web tiene una ip diferente, ahí sería más difícil de bloquear para mediafire. como te dije solo te estoy hablando de la teoría porque en sí esto es solo una prueba de concepto para un proyecto antiguo que ya no me interesa.

**Comment by timoteo1994** [comment]
wao es verdad es muy interesante claro asi diciendo cada usuario tendria 1000 reproducciones por archivo, bueno gracias intentare pasar a javascript y gracias por su ayuda crei que la url era diferente pasado las 1000 reproducciones pero nunca pese que bloqueaba ya que descargar si deja
